[package]
name = "hedge_jam_4"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"

[profile.dev.package."*"]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


